name: zeder
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+5

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.7
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  material_design_icons_flutter: ^6.0.7096
  carousel_slider: ^4.2.1
  audioplayers: ^3.0.1
  flutter_audio_waveforms: ^1.2.1+8
  video_player: ^2.5.2
  solid_bottom_sheet: ^0.1.10
  flutter_rating_bar: ^4.0.0
  provider: ^6.0.5
  firebase_auth: 4.2.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.0.15
  firebase_crashlytics: ^3.0.16
  email_validator: ^2.0.1
  firebase_messaging: ^14.6.1
  intl: any
  rounded_loading_button: ^2.1.0
  brasil_fields: 1.12.0
  internet_connection_checker: ^1.0.0+1
  connectivity: ^3.0.6
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.4.0
  url_launcher: ^6.0.14
  flutter_email_sender: ^5.0.2
  flutter_localization: ^0.1.13


  design_system:
    git:
      url: https://github.com/caiobraga/packages.git
      path: design_system

  core:
    git:
      url: https://github.com/caiobraga/packages.git
      path: core

  ui:
    git:
      url: https://github.com/caiobraga/packages.git
      path: ui


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/housie.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/housie.png.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  assets:
    - assets/

  uses-material-design: true
  generate: true






