class ServicoRepo{
  List<Map<String, dynamic>> servico_repo = [
    {
      "id": "123",
      "dataCadastro": "2023-05-14T08:00:00Z",
      "idTipoServico": "1",
      "idCliente": "client1",
      "idCidade": "1",
      "descricao": "This is a sample service description",
      "valorInicial": 100.0,
      "valorFinal": 200.0,
      "dataInicial": "2023-06-01T08:00:00Z",
      "dataFinal": "2023-06-30T08:00:00Z",
      "flgDatasFlexiveis": false,
      "status": "Open",
      "idsPropostasRecebidas": ["1314", "1516"],
      "idPropostaAceita": "",
      "idPrestador": "prestador1",
      "dataPropostaAceita": "",
      "flgAvisoCliente": false,
      "flgAvisoPrestador": false,
      "idDisputa": ""
    },
    {
      "id": "1234",
      "dataCadastro": "2023-05-12T10:20:30Z",
      "idTipoServico": "2",
      "idCliente": "client2",
      "idCidade": "1",
      "descricao": "Fix a broken outlet",
      "valorInicial": 50.0,
      "valorFinal": 75.0,
      "dataInicial": "2023-06-01T08:00:00Z",
      "dataFinal": "2023-06-02T08:00:00Z",
      "flgDatasFlexiveis": false,
      "status": "Open",
      "idsPropostasRecebidas": ["xyz987", "pqr456"],
      "idPropostaAceita": "",
      "idPrestador": "prestador2",
      "dataPropostaAceita": "",
      "flgAvisoCliente": false,
      "flgAvisoPrestador": false,
      "idDisputa": ""
    },
    /*
  {
    "id": "ijkl9012",
    "dataCadastro": "2023-05-14T15:00:00Z",
    "idTipoServico": "gardener",
    "idCliente": "bob_smith",
    "idCidade": "san_francisco",
    "descricao": "Mow the lawn",
    "valorInicial": 50.0,
    "valorFinal": 60.0,
    "dataInicial": "2023-06-10T08:00:00Z",
    "dataFinal": "2023-06-11T08:00:00Z",
    "flgDatasFlexiveis": true,
    "status": "Open",
    "idsPropostasRecebidas": ["nop345", "qrs678"],
    "idPropostaAceita": "",
    "idPrestador": "",
    "dataPropostaAceita": "",
    "flgAvisoCliente": false,
    "flgAvisoPrestador": false,
    "idDisputa": ""
  },
  {
    "id": "123",
    "dataCadastro": "2023-05-14T08:00:00Z",
    "idTipoServico": "456",
    "idCliente": "789",
    "idCidade": "101112",
    "descricao": "This is a sample service description",
    "valorInicial": 100.0,
    "valorFinal": 200.0,
    "dataInicial": "2023-06-01T08:00:00Z",
    "dataFinal": "2023-06-30T08:00:00Z",
    "flgDatasFlexiveis": false,
    "status": "Open",
    "idsPropostasRecebidas": ["1314", "1516"],
    "idPropostaAceita": "",
    "idPrestador": "",
    "dataPropostaAceita": "",
    "flgAvisoCliente": false,
    "flgAvisoPrestador": false,
    "idDisputa": ""
  }*/
  ];
}
